export const REQUEST_DOCTORS_LIST = 'REQUEST_DOCTORS_LIST';
export const REQUEST_DOCTORS_LIST_SUCCESS = 'REQUEST_DOCTORS_LIST_SUCCESS';
export const REQUEST_DOCTORS_LIST_FAILED = 'REQUEST_DOCTORS_LIST_FAILED';

export const SELECT_DOCTOR = 'SELECT_DOCTOR';
export const TOGGLE_ALL_DOCTORS = 'TOGGLE_ALL_DOCTORS';
export const TOGGLE_DOCTORS_BY_TYPE = 'TOGGLE_DOCTORS_BY_TYPE';

export const REQUEST_PATIENTS_LIST = 'REQUEST_PATIENTS_LIST';
export const REQUEST_PATIENTS_LIST_SUCCESS = 'REQUEST_PATIENTS_LIST_SUCCESS';
export const REQUEST_PATIENTS_LIST_FAILED = 'REQUEST_PATIENTS_LIST_FAILED';

export const SELECT_PATIENT = 'SELECT_PATIENT';
export const REMOVE_PATIENT = 'REMOVE_PATIENT';

export const SELECT_DATE = 'SELECT_DATE';
export const TOGGLE_CALENDAR = 'TOGGLE_CALENDAR';

export const SET_TIME_FILTER = 'SET_TIME_FILTER';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const SHOW_APPOINTMENT = 'SHOW_APPOINTMENT';
export const CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT';

export const appointmentTypes = {
  PATIENT: 'PATIENT',
  STUDY: 'STUDY',
  PAPERWORK: 'PAPERWORK',
  OFF: "OFF",
  NOAPP: "NOAPP",
};

